(function(){
 'use strict';
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key='hrone-holiday-plans-v1';
 let plans=[{id:'CN2026',name:'中国区2026年节假日方案',region:'中国',year:'2026',rows:[{name:'元旦',legal:'是',start:'2026-01-01',end:'2026-01-01',duration:'0.0'},{name:'国庆节',legal:'是',start:'2026-10-01',end:'2026-10-03',duration:'0.0'}]},{id:'OS2026',name:'海外2026年节假日方案',region:'非中国',year:'2026',rows:[{name:'元旦',legal:'是',start:'2026-01-01',end:'2026-01-01',duration:'0.0'},{name:'耶稣受难日',legal:'否',start:'2026-04-03',end:'2026-04-03',duration:'0.0'}]}];
 try{const saved=JSON.parse(sessionStorage.getItem(key));if(Array.isArray(saved))plans=saved;}catch{}
 let draft=null,readonly=false,page=1,returnFocus=null,pendingDelete=null;
 const blank=()=>({name:'元旦',legal:'',start:'',end:'',duration:'0.0'});
 const saveState=()=>sessionStorage.setItem(key,JSON.stringify(plans));
 function render(){const rows=plans.filter(p=>p.name.includes($('#filterPlanName').value)&&(!$('#filterRegion').value||p.region===$('#filterRegion').value)&&(!$('#filterYear').value||p.year===$('#filterYear').value));page=Math.min(page,Math.max(1,Math.ceil(rows.length/10)));$('#holidayPlanRows').innerHTML=rows.slice((page-1)*10,page*10).map((p,i)=>`<tr><td class="seq">${(page-1)*10+i+1}</td><td title="${esc(p.name)}">${esc(p.name)}</td><td>${esc(p.region)}</td><td>${esc(p.year)}</td><td><div class="plan-row-actions">${['查看','编辑','删除','复制'].map(a=>`<button type="button" class="text-button" data-plan-action="${a}" data-plan-id="${esc(p.id)}">${a}</button>`).join('')}</div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">暂无符合条件的节假日方案</td></tr>';$('#planCount').textContent=`共 ${rows.length} 条，每页 10 条`;$('#planPages').innerHTML=`<button class="btn" data-page="${page-1}" ${page===1?'disabled':''}>‹</button><span class="current-page">${page}</span><button class="btn" data-page="${page+1}" ${page*10>=rows.length?'disabled':''}>›</button>`;}
 function renderEditor(){const names=['元旦','春节','清明节','劳动节','端午节','中秋节','国庆节','耶稣受难日'];$('#holidayRows').innerHTML=draft.rows.map((r,i)=>`<tr data-row="${i}"><td class="seq">${i+1}</td><td><select class="cell-control" data-key="name" ${readonly?'disabled':''}>${names.map(n=>`<option ${n===r.name?'selected':''}>${n}</option>`).join('')}</select></td><td><div class="legal-field"><div class="radio-group" role="radiogroup" aria-label="第${i+1}行是否法定">${['是','否'].map(v=>`<label><input type="radio" name="legal-${i}" value="${v}" ${r.legal===v?'checked':''} ${readonly?'disabled':''}>${v}</label>`).join('')}</div><div class="field-error">必填项不能为空</div></div></td><td><input class="date-control" data-key="start" type="date" value="${r.start}" ${readonly?'disabled':''}></td><td><input class="date-control" data-key="end" type="date" value="${r.end}" ${readonly?'disabled':''}></td><td><input class="duration-control" data-key="duration" type="number" min="0" max="24" step="0.5" value="${esc(r.duration)}" ${readonly?'disabled':''}></td><td><div class="row-actions"><button class="icon-btn remove" type="button" aria-label="删除第${i+1}行" ${readonly?'disabled':''}>−</button>${i===draft.rows.length-1?`<button class="icon-btn add" type="button" aria-label="新增一行" ${readonly?'disabled':''}>＋</button>`:''}</div></td></tr>`).join('');}
 function open(action,source){returnFocus=document.activeElement;readonly=action==='查看';draft=source?structuredClone(source):{id:'',name:'',region:'',year:String(new Date().getFullYear()),rows:[blank()]};if(action==='复制'){draft.id='';draft.name='';}$('#planTitle').textContent=action+'节假日方案';for(const [id,k] of [['planName','name'],['planRegion','region'],['planYear','year']]){$('#'+id).value=draft[k];$('#'+id).disabled=readonly;}$('#save').hidden=readonly;$('#cancel').textContent=readonly?'关闭':'取消';$('#planError').textContent='';renderEditor();$('#planOverlay').hidden=false;document.body.classList.add('locked');(readonly?$('#closePlan'):$('#planName')).focus();}
 function close(){ $('#planOverlay').hidden=true;$('#deleteOverlay').hidden=true;document.body.classList.remove('locked');returnFocus?.focus(); }
 $('#addPlan').onclick=()=>open('新增');$('#closePlan').onclick=$('#cancel').onclick=close;
 $('#queryPlans').onclick=()=>{page=1;render();};$('#resetPlans').onclick=()=>{['filterPlanName','filterRegion','filterYear'].forEach(id=>$('#'+id).value='');page=1;render();};
 $('#holidayRows').addEventListener('input',e=>{const tr=e.target.closest('[data-row]');if(!tr||readonly)return;const row=draft.rows[Number(tr.dataset.row)];if(e.target.type==='radio'){row.legal=e.target.value;tr.querySelector('.legal-field').classList.remove('invalid');}else if(e.target.dataset.key)row[e.target.dataset.key]=e.target.value;});
 $('#holidayRows').addEventListener('click',e=>{if(readonly)return;if(e.target.matches('.add')){draft.rows.push(blank());renderEditor();}if(e.target.matches('.remove')){if(draft.rows.length===1){showToast('至少保留一条节假日明细');return;}draft.rows.splice(Number(e.target.closest('[data-row]').dataset.row),1);renderEditor();}});
 $('#save').onclick=()=>{if(readonly)return;draft.name=$('#planName').value.trim();draft.region=$('#planRegion').value;draft.year=$('#planYear').value;const issues=[];if(!draft.name||!draft.region||!/^\d{4}$/.test(draft.year)||Number(draft.year)<2000||Number(draft.year)>2100)issues.push('请完整填写方案名称、地区和有效年份');draft.rows.forEach((r,i)=>{const legal=$(`#holidayRows [data-row="${i}"] .legal-field`);legal.classList.toggle('invalid',!r.legal);if(!r.legal)issues.push(`第${i+1}行请选择是否法定`);if(!r.start||!r.end||r.end<r.start)issues.push(`第${i+1}行请填写有效的起止日期`);else if(!r.start.startsWith(draft.year+'-')||!r.end.startsWith(draft.year+'-'))issues.push(`第${i+1}行日期须属于方案年份`);if(r.duration===''||!Number.isFinite(Number(r.duration))||Number(r.duration)<0||Number(r.duration)>24)issues.push(`第${i+1}行每日时长须为0至24小时`);});$('#planError').textContent=issues.join('；');if(issues.length)return;const i=plans.findIndex(p=>p.id===draft.id);if(i>=0)plans[i]=structuredClone(draft);else{draft.id=crypto.randomUUID();plans.unshift(structuredClone(draft));}saveState();close();page=1;render();showToast('节假日方案已保存（原型演示）');};
 $('#holidayPlanRows').onclick=e=>{const b=e.target.closest('[data-plan-action]');if(!b)return;const source=plans.find(p=>p.id===b.dataset.planId);if(b.dataset.planAction==='删除'){returnFocus=b;pendingDelete=source.id;$('#deleteMessage').textContent=`确定删除“${source.name}”吗？`;$('#deleteOverlay').hidden=false;document.body.classList.add('locked');$('#cancelDeletePlan').focus();}else open(b.dataset.planAction,source);};
 $('#cancelDeletePlan').onclick=close;$('#confirmDeletePlan').onclick=()=>{plans=plans.filter(p=>p.id!==pendingDelete);saveState();close();render();showToast('节假日方案已删除（原型演示）');};
 $('#planPages').onclick=e=>{const b=e.target.closest('[data-page]');if(b&&!b.disabled){page=Number(b.dataset.page);render();}};
 document.addEventListener('keydown',e=>{const overlay=!$('#deleteOverlay').hidden?$('#deleteOverlay'):!$('#planOverlay').hidden?$('#planOverlay'):null;if(!overlay)return;if(e.key==='Escape')close();if(e.key==='Tab'){const controls=[...overlay.querySelectorAll('button,input,select')].filter(n=>!n.disabled&&!n.hidden);if(e.shiftKey&&document.activeElement===controls[0]){e.preventDefault();controls.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===controls.at(-1)){e.preventDefault();controls[0].focus();}}});
 let timer;function showToast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,2200);}
 render();
})();
