(function(){
  "use strict";
  const initial={day:"restday",workday:{mode:"卡单交集",comp:"是",pay:true,timeoff:false,min:"1",cap:"",rest:"30",round:"向下取整",unit:"0.5"},restday:{mode:"卡单交集",comp:"是",pay:true,timeoff:false,dutyAllowance:true,dutyTimeoff:true,dutyHolidays:['春节','劳动节','国庆节'],threshold:"240",min:"1",cap:"",rest:"0",round:"向下取整",unit:"0.5"},holiday:{mode:"卡单交集",comp:"是",pay:true,timeoff:false,dutyAllowance:true,dutyTimeoff:true,dutyHolidays:['春节','劳动节','国庆节'],threshold:"240",min:"1",cap:"",rest:"0",round:"向下取整",unit:"0.5"}};
  const storageKey='hrone-overtime-plan-duty-v1';
  let saved=structuredClone(initial),state=structuredClone(initial),errors={};
  try{const value=JSON.parse(sessionStorage.getItem(storageKey));if(value?.workday&&value?.restday&&value?.holiday)saved=value;}catch{}
  // 与中国区节假日配置使用相同名称，日期由节假日配置维护。
  const holidayNames=['元旦','春节','清明节','劳动节','端午节','中秋节','国庆节'];
  const availableHolidays=()=>$('#planRegion').value==='中国区'?holidayNames:[];
  const names={workday:"工作日",restday:"公休日",holiday:"节假日"};
  // 配置项在当前页面直接展示。
  const $=s=>document.querySelector(s);
  function field(label,control,key,required){return `<div class="form-item"><span class="field-label">${required?'<b>*</b> ':''}${label}</span>${control}</div>`}
  function select(key,items){const s=state[state.day];return `<select data-key="${key}">${items.map(v=>`<option${s[key]===v?' selected':''}>${v}</option>`).join('')}</select>`}
  function number(key,placeholder="请输入"){return `<input type="number" min="0" step="any" data-key="${key}" value="${state[state.day][key]}" placeholder="${placeholder}">`}
  function check(key,text){return `<label><input type="checkbox" data-key="${key}"${state[state.day][key]?' checked':''}>${text}</label>`}
  function holidayField(){const s=state[state.day];return `<div class="form-item" id="dutyHolidayField"><span class="field-label"><b>*</b> 值班补贴适用节假日</span><details class="holiday-picker${errors.holidays?' invalid':''}" id="dutyHolidayPicker"><summary aria-label="值班补贴适用节假日" aria-describedby="dutyHolidayError">${s.dutyHolidays.length?s.dutyHolidays.join('、'):'请选择'}</summary><div class="holiday-options">${availableHolidays().map(name=>`<label><input type="checkbox" data-holiday value="${name}"${s.dutyHolidays.includes(name)?' checked':''}>${name}</label>`).join('')||'<span class="helper">请先选择划分区域</span>'}</div></details><span class="field-error" id="dutyHolidayError">${errors.holidays?'必填项不能为空':''}</span></div>`}
  function render(){const s=state[state.day],duty=state.day!=="workday",inter=s.mode==="卡单交集";document.querySelectorAll('.day-tab[data-day]').forEach(x=>{x.classList.toggle('active',x.dataset.day===state.day);x.setAttribute('aria-selected',x.dataset.day===state.day)});$('#dayPanel').innerHTML=`<section class="config-section"><div class="section-head">加班配置</div><div class="definition"><strong>${names[state.day]}定义</strong>${state.day==="holiday"?'按法定节假日，班次属性为节假日':'按排班，班次属性为'+names[state.day]}</div><div class="form-grid">${field('加班方式',select('mode',['提交加班申请','无需申请按打卡计算加班','卡单交集']),'mode',true)}${field('加班是否有补偿',`<div class="choice-group"><label><input type="radio" name="comp" data-key="comp" value="是"${s.comp==='是'?' checked':''}>是</label><label><input type="radio" name="comp" data-key="comp" value="否"${s.comp==='否'?' checked':''}>否</label></div>`,'',true)}${s.comp==='是'?field('补偿方式',`<div class="choice-group">${check('pay','加班费')}${check('timeoff','调休假')}</div>`,'',true):'<div></div>'}${duty?field('允许加班时间','<select><option>请选择</option></select>','',true):''}${field('最小加班时长（小时）',number('min'),'',true)}${duty&&s.comp==='是'?field('值班补贴方式',`<div class="choice-group">${check('dutyTimeoff','调休')}${check('dutyAllowance','津贴')}</div>`,'duty',false):''}${duty&&s.comp==='是'&&(s.dutyAllowance||s.dutyTimeoff)?holidayField():''}${duty&&s.comp==='是'&&s.dutyAllowance?field('津贴计发门槛（分钟）',number('threshold')+`<span class="field-error">${errors.threshold?'必填项不能为空':''}</span>`,'threshold',true):''}${field('单日加班时长上限（小时）',number('cap'),'cap',false)}${field('班后不计加班时长（分钟）',number('rest')+'<span class="helper">从当天应下班时间起，指定分钟内不计加班；仅扣除重叠部分。</span>','rest',false)}</div></section><section class="config-section"><div class="section-head">加班计算</div><div class="form-grid">${field('每日加班时长计算规则',inter?'<input class="readonly" disabled value="按申请与有效打卡时段取交集">':'<select><option>请选择</option></select>','',true)}${field('每日总工时计算规则','<select><option>请选择</option></select>','',true)}${field('出勤时长（补偿后）计算规则','<select><option>请选择</option></select>','',false)}${field('取整方式',select('round',['向下取整','向上取整','四舍五入']),'',true)}${field('取整时长（小时）',number('unit'),'',false)}</div></section>`;}
  function openEditor(edit){state=structuredClone(edit?saved:initial);$('#planName').value=edit?'中国区加班方案':'';$('#planRegion').value=edit?'中国区':'';if(!edit)for(const day of ['restday','holiday']){state[day].dutyAllowance=false;state[day].dutyTimeoff=false;state[day].dutyHolidays=[];state[day].threshold='';}errors={};$('#editorTitle').textContent=edit?'编辑加班方案':'新增加班方案';$('#editor').hidden=false;state.day='restday';render()}
  $('#planRegion').addEventListener('change',()=>{for(const day of ['restday','holiday'])state[day].dutyHolidays=state[day].dutyHolidays.filter(name=>availableHolidays().includes(name));errors={};render();});
  $('#addPlan').onclick=()=>openEditor(false);document.addEventListener('click',e=>{if(e.target.classList.contains('editPlan'))openEditor(true);if(e.target.matches('.day-tab[data-day]')){state.day=e.target.dataset.day;render()}});
  $('#dayPanel').addEventListener('input',e=>{const key=e.target.dataset.key;if(!key)return;state[state.day][key]=e.target.type==='checkbox'?e.target.checked:e.target.value});
  $('#dayPanel').addEventListener('change',e=>{const s=state[state.day];if(e.target.hasAttribute('data-holiday')){s.dutyHolidays=holidayNames.filter(name=>name===e.target.value?e.target.checked:s.dutyHolidays.includes(name));$('#dutyHolidayPicker summary').textContent=s.dutyHolidays.join('、')||'请选择';errors.holidays=false;$('#dutyHolidayError').textContent='';$('#dutyHolidayPicker').classList.remove('invalid');return;}if(['mode','comp','dutyAllowance','dutyTimeoff'].includes(e.target.dataset.key)){if(!s.dutyAllowance&&!s.dutyTimeoff||s.comp==='否'){s.dutyHolidays=[];errors={};}if(!s.dutyAllowance||s.comp==='否')s.threshold='';render();}});
  function savePlan(){errors={};for(const day of ['restday','holiday']){const s=state[day];if(s.comp!=='是')continue;const invalidHolidays=(s.dutyAllowance||s.dutyTimeoff)&&!s.dutyHolidays.length,invalidThreshold=s.dutyAllowance&&s.threshold==='';if(invalidHolidays||invalidThreshold){state.day=day;errors={holidays:invalidHolidays,threshold:invalidThreshold};render();const target=invalidHolidays?$('#dutyHolidayPicker summary'):$('[data-key="threshold"]');target.focus();target.scrollIntoView({block:'center'});return;}}saved=structuredClone(state);sessionStorage.setItem(storageKey,JSON.stringify(saved));closeEditor();toast('加班方案已保存（原型演示）');}
  function closeEditor(){$('#editor').hidden=true}$('#closeEditor').onclick=closeEditor;$('#cancelEditor').onclick=closeEditor;$('#savePlan').onclick=savePlan;$('#resetQuery').onclick=()=>{$('#queryName').value='';$('#queryRegion').selectedIndex=0;$('#queryStatus').selectedIndex=0};$('#runQuery').onclick=()=>toast('已按当前条件查询');let timer;function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,2200)}document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeEditor()}});
}());
